version: "3.7"
services:
    kong-db:
        image: postgres:9.6-alpine
        container_name: kong-db
        env_file:
            - kong-db.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 2s
            retries: 15

    kong:
        image: "kong:${TAG-latest}"
        container_name: kong
        env_file:
            - ./kong.env
        depends_on:
            - kong-db
        ports:
            - 127.0.0.1:8001:8001
            - 127.0.0.1:8444:8444
            - 8000:8000
            - 8443:8443
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 5s
            timeout: 2s
            retries: 15


    konga-init:
        image: pantsel/konga
        command: "-c prepare -a postgres -u postgresql://kong:kong@kong-db:5432/konga_db"
        depends_on:
            - kong-db

    konga:
        image: pantsel/konga
        container_name: konga
        depends_on:
            - kong-db
        env_file:
            - konga.env
        ports:
            - 1337:1337
